[XmlWinEventLog:Security]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)\s*(?=<Event[\s>])
TRUNCATE = 0
MAX_TIMESTAMP_LOOKAHEAD = 64
TIME_PREFIX = <TimeCreated SystemTime="
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%QZ
KV_MODE = xml
AUTO_KV_XML = true
REPORT-xml4688-fields = xml4688_eventid, xml4688_newprocess, xml4688_parentprocess, xml4688_commandline

