[xml4688_eventid]
REGEX = (?ms)<EventID>\s*(\d+)\s*</EventID>
FORMAT = EventID::$1

[xml4688_newprocess]
REGEX = (?ms)<Data Name='NewProcessName'>\s*([^<]+)\s*</Data>
FORMAT = NewProcessName::$1

[xml4688_parentprocess]
REGEX = (?ms)<Data Name='ParentProcessName'>\s*([^<]+)\s*</Data>
FORMAT = ParentProcessName::$1

[xml4688_commandline]
REGEX = (?ms)<Data Name='CommandLine'>\s*([^<]*)\s*</Data>
FORMAT = CommandLine::$1

